<a href="https://colab.research.google.com/github/fajarkhalid/Data-Science-and-Analytics/blob/main/20SW049_LAB04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Task1

import numpy as np
X = np.arange(2, 34, 2).reshape(4, 4)
print(X)

[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [2]:
#Task2

import numpy as np

X = np.arange(1, 26).reshape(5, 5)
Y = X[X % 2 != 0]

print(X)
print(Y)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [3]:
#Task3

import numpy as np
X = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4))

print(X)


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]


In [5]:
#Task4

from google.colab import drive
drive.mount('/NumPy.ipnyb')

import numpy as np

# Create a 1000x20 ndarray with random integers in the range [0, 5001)
X = np.random.randint(0, 5001, size=(1000, 20))
# Print the shape of X
print(X.shape)

# Calculate the average of the values in each column of X
ave_cols = np.mean(X, axis=0)

# Calculate the standard deviation of the values in each column of X
std_cols = np.std(X, axis=0)


print("Shape of ave_cols:", ave_cols.shape)
print("Shape of std_cols:", std_cols.shape)

# Mean normalize X
X_norm = (X - ave_cols) / std_cols

print("Mean normalized X:")
print(X_norm)

# Print the average of all the values of X_norm
ave_all_values = np.mean(X_norm)
print("Average of all values in X_norm:", ave_all_values)

# Print the average of the minimum value in each column of X_norm
ave_min_values = np.mean(np.min(X_norm, axis=0))
print("Average of minimum values in each column of X_norm:", ave_min_values)

# Print the average of the maximum value in each column of X_norm
ave_max_values = np.mean(np.max(X_norm, axis=0))
print("Average of maximum values in each column of X_norm:", ave_max_values)

# We create a random permutation of integers 0 to 4
np.random.permutation(5)

# Create a random permutation of row indices of X_norm
row_indices = np.random.permutation(X_norm.shape[0])

print("Random permutation of row indices:", row_indices)


# Define the ratios for training, cross-validation, and test sets
train_ratio = 0.6
cross_val_ratio = 0.2
test_ratio = 0.2

# Calculate the sizes of each set based on the ratios
num_rows = X_norm.shape[0]
num_train = int(train_ratio * num_rows)
num_cross_val = int(cross_val_ratio * num_rows)
num_test = int(test_ratio * num_rows)

# Use row_indices to split the data into sets
X_train = X_norm[row_indices[:num_train]]
X_crossVal = X_norm[row_indices[num_train:num_train + num_cross_val]]
X_test = X_norm[row_indices[num_train + num_cross_val:]]

print("X_train shape:", X_train.shape)
print("X_crossVal shape:", X_crossVal.shape)
print("X_test shape:", X_test.shape)


Mounted at /NumPy.ipnyb
(1000, 20)
Shape of ave_cols: (20,)
Shape of std_cols: (20,)
Mean normalized X:
[[-0.25251504  0.58745965 -0.49544172 ... -0.63692113  0.26970259
  -0.40664042]
 [-1.49318728 -0.78146082  0.87658409 ...  0.43946033  0.63639543
  -1.6038113 ]
 [ 1.60883174  0.31367555  0.90508108 ... -0.03249154 -0.03610805
   1.43994897]
 ...
 [-0.18415285 -1.48617549  1.33670622 ...  1.56069103  1.20882815
  -1.29051355]
 [ 0.35597614  0.54206177 -0.10899473 ...  0.97627109  1.32849319
   0.26975075]
 [-0.44812567 -1.19004167 -0.43636259 ... -1.69881285 -1.71351787
   1.48905303]]
Average of all values in X_norm: 3.552713678800501e-18
Average of minimum values in each column of X_norm: -1.7366392652239295
Average of maximum values in each column of X_norm: 1.7118702232023928
Random permutation of row indices: [998 921 785 444 769 394 485 345 740 427 833 191 536 670 966  95 669  82
 116 142 651  44 896  50 500 327 503 971 731 851 746 417 859 125 402  10
 520 944 897 928 141 497 